name: cluster-spark-rss

services:
  spark-master-rss:
    container_name: spark-master-rss
    build: .
    image: spark-image-rss
    entrypoint: ['./entrypoint.sh', 'master']
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 5s
      timeout: 3s
      retries: 3
    volumes:
      - ./datasets:/opt/spark/dados
      - ./projetos:/opt/spark/jobs
      - ./:/opt/spark/repo
      - spark-logs:/opt/spark/spark-events
      
    env_file:
      - .env.spark
    ports:
      - '9090:8080'   # Spark Master UI
      - '7077:7077'   # Spark Master port (cluster)

  spark-history-rss:
    container_name: spark-history-rss
    image: spark-image-rss
    entrypoint: ['./entrypoint.sh', 'history']
    depends_on:
      - spark-master-rss
    env_file:
      - .env.spark
    volumes:
      - spark-logs:/opt/spark/spark-events
    ports:
      - '18080:18080' # Spark History Server UI

  spark-worker-rss:
    image: spark-image-rss
    entrypoint: ['./entrypoint.sh', 'worker']
    depends_on:
      - spark-master-rss
    env_file:
      - .env.spark
    volumes:
      - ./datasets:/opt/spark/dados
      - ./projetos:/opt/spark/jobs
      - ./:/opt/spark/repo
      - spark-logs:/opt/spark/spark-events

  # Jupyter dentro do Docker, na mesma rede do cluster
  jupyter-rss:
    container_name: jupyter-rss
    image: spark-image-rss
    depends_on:
      - spark-master-rss
    # Sobrescreve o entrypoint do Spark (que espera master/worker/history)
    entrypoint: ["jupyter"]
    command:
      - "lab"
      - "--allow-root"
      - "--ip=0.0.0.0"
      - "--port=8888"
      - "--no-browser"
      - "--NotebookApp.token="
      - "--NotebookApp.password="
      - "--NotebookApp.allow_origin=*"
      - "--NotebookApp.base_url=/"              
    environment:
      - PYSPARK_PYTHON=python3
    volumes:
      - ./notebooks:/workspace/notebooks
      - ./datasets:/opt/spark/dados
      - ./projetos:/opt/spark/jobs
      - ./:/opt/spark/repo
      - spark-logs:/opt/spark/spark-events
    working_dir: /workspace/notebooks
    ports:
      - "8888:8888"

volumes:
  spark-logs:
