spark.master                           spark://spark-master-rss:7077
spark.eventLog.enabled                 true
spark.eventLog.dir                     /opt/spark/spark-events
spark.history.fs.logDirectory          /opt/spark/spark-events
spark.driver.extraJavaOptions    	   -Dlog4j.logLevel=ERROR
spark.executor.extraJavaOptions  	   -Dlog4j.logLevel=ERROR
